### ISSUE TITLE
Improve UI for tablet/mobile view. 

### ISSUE THREAD

**Issue by anweshknayak** [HackInTheNorth/hackinthenorth.github.io#107]
![screenshot from 2017-02-23 15 35 07](https://cloud.githubusercontent.com/assets/8139783/23254472/34cbb57a-f9de-11e6-840b-1b0dc2b4f0b4.png)

@gauthamzz

**Comment by gauthamzz** [comment]
why was it closed ? @anweshknayak we will solve it , in time :smile:

**Comment by anweshknayak** [comment]
@gauthamzz I didn't see #67 . It has already been mentioned there.

**Comment by hackerkid** [comment]
I am closing #67. It's too outdated and most of the problems in that issue is fixed.
