### ISSUE TITLE
Add Coming Soon Page

### ISSUE THREAD

**Issue by yasharmaster** [HackInTheNorth/hackinthenorth.github.io#115]
We can take inspiration from landing page of [HackRU website](http://www.hackru.org/). It will have
- [this image](https://www.facebook.com/photo.php?fbid=1437692832928982&set=a.383267208371555.90198.100000648364289&type=3&theater) in the background
- a subscribe button

@gauthamzz

**Comment by Anupam-dagar** [comment]
I would like to work on it

**Comment by Anupam-dagar** [comment]
should I change it a little or do a clone of it?

**Comment by yasharmaster** [comment]
@Anupam-dagar 
Feel free to be creative and make changes. Just make sure that the page is responsive.

**Comment by Anupam-dagar** [comment]
@yasharmaster I hope it's not required urgently, I can create a pull request on Sunday.

**Comment by gauthamzz** [comment]
@Anupam-dagar Its okay but dont take more time, take help if needed :+1:

**Comment by Anupam-dagar** [comment]
http://anupamdagar.me/hack-in-the-north-preview-repo/comingsoon/
Take a look at it and suggest changes.I think the colored logo is not going well with the bg image.Is there need of any other buttons.Minor fixes like hyper link and overlay fix for all screen will be done.

**Comment by yasharmaster** [comment]
Looks good to me @Anupam-dagar  :smile: We can also
- remove the colored logo for now
- try out other fonts for COMING SOON and see which looks the best
- move coming soon to the left half of the page 
- put a button "Subscribe for updates" below coming soon
- on the right half put a heading "Hack In The North 3.0" and "IIIT Allahabad" below it

**Comment by gauthamzz** [comment]
@Anupam-dagar  could you try making the whole page fit in one screen ?
