### ISSUE TITLE
Create Team Page

### ISSUE THREAD

**Issue by yasharmaster** [HackInTheNorth/hackinthenorth.github.io#122]
2018 Hack in the North Team

**Comment by gauthamzz** [comment]
@aswanthkoleri is assigned

**Comment by gauthamzz** [comment]
@aswanthkoleri update here :confused:

**Comment by aswanthkoleri** [comment]
@gauthamzz time to close this ! ;-p

**Comment by gauthamzz** [comment]
No :smile:

**Comment by gauthamzz** [comment]
I closed it first @mubaris :smile:
