### ISSUE TITLE
Enhance font-family and color

### ISSUE THREAD

**Issue by SaptakS** [HackInTheNorth/hackinthenorth.github.io#13]
Please look into the font-family, font-size and other text properties to make it prominent.

**Comment by hackerkid** [comment]
Fixed in https://github.com/HackInTheNorth/hackinthenorth.github.io/pull/15

**Comment by pradyumna1** [comment]
guys, I have updated the font again.. revert or tell me the font-family if you don't like it

**Comment by SaptakS** [comment]
This looks good as well..
