### ISSUE TITLE
Todo list 

### ISSUE THREAD

**Issue by Anupam-dagar** [HackInTheNorth/hackinthenorth.github.io#133]
~~fix faq on click jerk.~~
~~create a sponsor section~~
loader

**Comment by yasharmaster** [comment]
@Anupam-dagar 
Also add a loader to the site.

**Comment by Anupam-dagar** [comment]
I have an idea for the loader, will implement it at last.

**Comment by gauthamzz** [comment]
@yasharmaster @Anupam-dagar can we have a non fancy minimal one or the gears in the logo for the loader :smile: Just a suggestion.

Anyway great work guys, we have had a lot of progress

**Comment by Anupam-dagar** [comment]
yeah that will also look good
what I was thinking that we can have the svg of the logo and logo starts drawing itself and finally color fill as the loader.
something like this
https://codepen.io/kiyutink/pen/ZpEZAq?q=svg+draw&limit=all&type=type-pens

**Comment by gauthamzz** [comment]
Its fine :) white bg.
