### ISSUE TITLE
About section 

### ISSUE THREAD

**Issue by gauthamzz** [HackInTheNorth/hackinthenorth.github.io#137]
Idk what happened this is weird 

![deepinscreenshot_20171108234220](https://user-images.githubusercontent.com/12110844/32566656-9c326bde-c4de-11e7-996e-bb115b5793f6.png)

So much space is there before the about section.

**Comment by Anupam-dagar** [comment]
i fixed it's centering.Making a PR

**Comment by gauthamzz** [comment]
I was wondering,if you could get some first year dev's they could help in simple issues if they want.

**Comment by gauthamzz** [comment]
closed at #138

**Comment by gauthamzz** [comment]
closed at #138
