### ISSUE TITLE
Add code of conduct 

### ISSUE THREAD

**Issue by gauthamzz** [HackInTheNorth/hackinthenorth.github.io#141]

**Comment by OrionStar25** [comment]
Review #144 please.

**Comment by gauthamzz** [comment]
This is solved in #144 but other issues which are solved in at are unfortunately not what we wanted. So make a new PR for only #141.

**Comment by OrionStar25** [comment]
Review #145 please.

**Comment by gauthamzz** [comment]
thanks :+1:
