### ISSUE TITLE
FAQ going out of bound

### ISSUE THREAD

**Issue by gauthamzz** [HackInTheNorth/hackinthenorth.github.io#142]

**Comment by OrionStar25** [comment]
PR #144  has faq handled too.

**Comment by gauthamzz** [comment]
I'm sorry this was not what was wanted . Please do ask what the issue is more clearly before solving. And since you are new please solve one issue at a time. There is no hurry :shell:

**Comment by OrionStar25** [comment]
I'll try to fix this now. You want it to not overflow after the screen has been resized right?

**Comment by gauthamzz** [comment]
When some Faq is opened it goes out of screen size .  Example given below :arrow_down: 
![deepinscreenshot_20171112153838](https://user-images.githubusercontent.com/12110844/32697849-95bce958-c7bf-11e7-8d9c-6b2908001603.png)

**Comment by gauthamzz** [comment]
remove code of conduct from nav bar as well :)

**Comment by gauthamzz** [comment]
solved
