### ISSUE TITLE
add iiita and aparoksha logo in the left most section of the landing page

### ISSUE THREAD

**Issue by hackerkid** [HackInTheNorth/hackinthenorth.github.io#19]

**Comment by hackerkid** [comment]
@pradyumna1 @vampcoder

**Comment by faheemzunjani** [comment]
I think this issue can be closed now.

**Comment by hackerkid** [comment]
Fixed in https://github.com/HackInTheNorth/hackinthenorth.github.io/pull/28  https://github.com/HackInTheNorth/hackinthenorth.github.io/pull/27
