### ISSUE TITLE
Image for Hasura in special rewards section is not available

### ISSUE THREAD

**Issue by pradeepgangwar** [HackInTheNorth/hackinthenorth.github.io#277]
- Image exists in the folder but on opening it gives error that image in not in png format. We need to fix it ASAP.
- Also link to InfotechHub in sponsors section is wrong.

![screenshot-2018-2-19 hack in the north 3 0](https://user-images.githubusercontent.com/21259802/36369922-1416caa6-1583-11e8-95c8-e0b6b4d5dead.png)

**Comment by pradeepgangwar** [comment]
@MubarisNK my browser Firefox Developer Edition and platform is Ubuntu 16.04

**Comment by gauthamzz** [comment]
hasrua doesnt come in firefox @Anupam-dagar

**Comment by pradeepgangwar** [comment]
@gauthamzz @Anupam-dagar who is doing this?

**Comment by Anupam-dagar** [comment]
@pradeepgangwar this has been resolved.

**Comment by pradeepgangwar** [comment]
@Anupam-dagar Follow good practice, i.e. if your commit resolves any PR. Mention Fixes #issue-no at the end of commit message. So that issue closes itself. CC- @gauthamzz

**Comment by Anupam-dagar** [comment]
Thanx for the path to enlightenment :stuck_out_tongue: :smile: @pradeepgangwar

**Comment by Anupam-dagar** [comment]
@gauthamzz please close this
