### ISSUE TITLE
Site is taking too long to load

### ISSUE THREAD

**Issue by gauthamzz** [HackInTheNorth/hackinthenorth.github.io#279]
- [ ] compress all images
- [ ] apply lazy loading to all images.
- [ ] minify css and js

**Comment by pradeepgangwar** [comment]
I am also facing this problem.

**Comment by Anupam-dagar** [comment]
all images are compressed, lazy loading is there, minification needs to be done again.

**Comment by gauthamzz** [comment]
![deepinscreenshot_select-area_20181023224306](https://user-images.githubusercontent.com/12110844/47378321-66931380-d715-11e8-9162-e95af27b5164.png)
Do an audit to the website, its less than normal. 

I suggest you use a CI like lighthouse, before merging PR

**Comment by Anupam-dagar** [comment]
I think we can do that for the main website.
