### ISSUE TITLE
404 error on landing page is fitting?

### ISSUE THREAD

**Issue by SaptakS** [HackInTheNorth/hackinthenorth.github.io#347]
The moment I go to the landing page, the first thing that greets me is a monitor with a 404 error. A 404 error suggests that I am in the wrong place. But given the other details in the page, I am guessing that it is the hack in the north website. So to me, a 404 error in the top most section of landing page is very contradictory. Maybe something like "Loading Soon...." or "Stay tuned for more" makes more sense.

**Comment by pani-vishal** [comment]
Ohh, that makes sense. We'll look into it. Thanks!

**Comment by gauthamzz** [comment]
Don't think it's nice to close issues before they are solved. Why put an issue if no one is going to care.

**Comment by pani-vishal** [comment]
We got it fixed. Also, we'll be replacing the coming soon site with the actual one tomorrow evening.
