### ISSUE TITLE
//*[@id="regBtn"]/center should be removed

### ISSUE THREAD

**Issue by sidgupta234** [HackInTheNorth/hackinthenorth.github.io#38]
Last date of registration has passed, hence the 'Register Now' option should be removed.

**Comment by pradyumna1** [comment]
@hackerkid  we can replace it with a link to list of selected participants.

**Comment by hackerkid** [comment]
@pradyumna1 Yeah. I will get the doc ready.

**Comment by hackerkid** [comment]
Fixed in https://github.com/HackInTheNorth/hackinthenorth.github.io/commit/480225fe42ddbbe7c3e440032bfe7f29ddd4222d
