### ISSUE TITLE
Add / modify/remove these features (suggestions) 

### ISSUE THREAD

**Issue by sameer2800** [HackInTheNorth/hackinthenorth.github.io#67]
1) remove  navigation buttons from the bottom and make left buttons immovable . (to avoid redundancy)
2) Increase the size of the logo in the middle and bring it to the center (vertically)
3) at the bottom of home page, add 2 buttons ,one for subscribe me and other for become a campus ambassador . 
(subscribe me is needed for short period of time until we open registrations )  .

**Comment by pradyumna1** [comment]
@yasharmaster  @sahilhindwani me and @sameer2800  discussed about this last night. Don't do this for now. These were the changes that we have to do:
1) We need a proper navbar. 
So please remove current navbar. It looks good for mobile. For desktop we need to use something like this http://codepen.io/BuiltBySam/pen/merjWp. Each link will be in different color just they are right now. @sahilhindwani  this is your task.
2) We have to add subscribe and campus ambassador buttons just below the logo. @yasharmaster  please do this today. 
Now, the entire landing section must come in a single viewport to improve UX. Take care of this thing.
3) Meanwhile @shubham-padia can you please work on mobile site? We will need to add media queries.  I will help you on this.
4) We need to add some small animations. let's discuss this today evening. You can see this site : http://2016f.pennapps.com/ It looks awesome in mobile. http://www.jqueryscript.net/demo/Cool-Revealing-Navigation-with-Page-Tilt-Effect-Using-jQuery-CSS3/ 
5) We nned to add links of our facebook and twitter.  Something like this will look fine: https://medium.freecodecamp.com/code-briefing-using-darth-vader-to-explain-react-cafd5c8d2ce6#.jfddwknf4
