### ISSUE TITLE
nav bar is broken

### ISSUE THREAD

**Issue by gauthamzz** [HackInTheNorth/hackinthenorth.github.io#74]
![deepinscreenshot20161020172512](https://cloud.githubusercontent.com/assets/12110844/19558865/5b3e8c0c-96ea-11e6-9a4d-e18331e05f62.png)

**Comment by pradyumna1** [comment]
I have updated the navbar. I tried many designs, but most of them were not looking good. Let's go with this one now. Will update if any better and good looking idea comes later.
