### ISSUE TITLE
Landing viewport irresponsive

### ISSUE THREAD

**Issue by magician03** [HackInTheNorth/hackinthenorth.github.io#80]
![screenshot from 2016-10-24 18 28 42](https://cloud.githubusercontent.com/assets/15110387/19646520/683dce92-9a17-11e6-8226-9f27bbd532ee.png)

Landing viewport along with timer and navbar items are over-lappping improperly

**Comment by pradyumna1** [comment]
@magician03 Not only the landing viewport, the entire website is unresponsive for now. We were thinking of focusing on laptop/desktop part first. After next update we will work on making it responsive for mobile users. 😄

**Comment by magician03** [comment]
@pradyumna1 not for mobile users alone, its looking awkward even for screens with `m` size ( around 13 ich ), why not simply use materialize or bootstrap.

**Comment by pradyumna1** [comment]
@magician03 too mainstream!! 😏
