### ISSUE TITLE
Too many errors in chrome-dev-console 

### ISSUE THREAD

**Issue by magician03** [HackInTheNorth/hackinthenorth.github.io#81]
![screenshot from 2016-10-24 18 31 08](https://cloud.githubusercontent.com/assets/15110387/19646607/d1ed5c54-9a17-11e6-844a-b0872f8690e0.png)

Errors are logged into console upon scrolling through the page and the count is increasing with time. Might be some serious issue with the scripts used.

**Comment by pradyumna1** [comment]
@magician03 this is due to some mistakes in use of selectors in nav-bar's js code. Thanks for notifying. They have been fixed in coming update. 😄
