### ISSUE TITLE
Add Sponsors as they come

### ISSUE THREAD

**Issue by pradyumna1** [HackInTheNorth/hackinthenorth.github.io#95]
Divide them according to their sponsorship levels: 
1) Github is title sponsor, keep their logo a little bigger
2) Platinum: Hackster.io
3) Gold: gitlab, KPT
4) Silver RestDB
5) Platform sponsor: Hackerearth
6) All the remaining ones will be patron
@yasharmaster, handle this task from now on.

**Comment by hackerkid** [comment]
+ Media Partner: GeeksForGeeks

**Comment by SaptakS** [comment]
@yasharmaster I think we should not mark gold, silver and patron separately. What I suggest is Title sponsor stays the biggest. Followed by platinum sponsor. And then everyone has similar sizes and we mention the level on the tooltip. @pradyumna1 @hackerkid what do you say?

**Comment by SaptakS** [comment]
And media partner, platform partner has to be different. That I agree.

**Comment by hackerkid** [comment]
I think Platinum Gold and silver sponsors deserved to be mentioned as it is as they are giving money.We will stick to this format. 

https://us.pycon.org/2016/sponsors/
